name: Daily Dish Generation

on:
  schedule:
    - cron: "0 6 * * *" # 06:00 UTC daily
  workflow_dispatch: {}

concurrency:
  group: daily-dish-generation
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create .env.local
        run: |
          cat > .env.local << 'EOF'
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          DAILY_COST_CAP_USD=${{ secrets.DAILY_COST_CAP_USD }}
          TARGET_BUFFER_DAYS=${{ secrets.TARGET_BUFFER_DAYS }}
          EOF

      - name: Run daily generator
        run: npm run daily-generate
